spring:
  application:
    name: "CommunityHealthManagement"
  datasource:
    url: jdbc:mysql://localhost/community_health?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: "root"
    password: "123456"

  data:
    redis:
      database: 0
      port: 6379
      host: localhost

mybatis:
  configuration:
    map-underscore-to-camel-case: true

email:
  user: 3583215615@qq.com
  #授权码
  code: mcwvvlrqfrdccjif
  host: smtp.qq.com
  auth: true