spring:
  application:
    name: "CommunityHealthManagement"
  datasource:
    url: jdbc:mysql://localhost/community_health?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: "root"
    password: "123456"

  data:
    redis:
      port: 6379
      host: localhost

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: per.yy.communityhealthmanagement.entity
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true

email:
  user: 3583215615@qq.com
  #授权码
  code: mcwvvlrqfrdccjif
  host: smtp.qq.com
  auth: true